spring:
  application:
    name: storm-shop-authentication
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://storm-shop-db;databaseName=resources
    username: SA
    password: Nguyenbaoloc1995
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://storm-shop-eureka-server:8761/eureka}
  instance:
    preferIpAddress: true