version: '3.8'
services:
  storm-shop-db-init:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Nguyenbaoloc1995"
      ACCEPT_EULA: "Y"
    volumes:
      - storm-shop-mssql-data:/var/opt/mssql/data
      - storm-shop-mssql-log:/var/opt/mssql/log
      - storm-shop-mssql-log:/var/opt/mssql/secrets
volumes:
  storm-shop-mssql-data:
  storm-shop-mssql-log:
  storm-shop-mssql-secrets: