spring:
  application:
    name: storm-shop-gateway
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://storm-shop-eureka-server:8761/eureka}
  instance:
    preferIpAddress: true